### ISSUE TITLE
Document the used resources

### ISSUE THREAD

**Issue by alexanderadam** [erebe/personal-server#16]
Hi @erebe,

thank you so much for sharing your configuration.
Could you document the currently used resources (roughly how much CPU / Memory).

I guess it would be great to see that.

**Comment by erebe** [comment]
![image](https://user-images.githubusercontent.com/854278/117534274-ed1c5180-aff0-11eb-9524-3992c0e3b894.png)
![image](https://user-images.githubusercontent.com/854278/117534287-f86f7d00-aff0-11eb-871a-ece2923bc81b.png)

here you are

**Comment by alexanderadam** [comment]
Perfect. Thank you! :pray:
