### ISSUE TITLE
Consider managing your cluster with Flux and Renovate

### ISSUE THREAD

**Issue by onedr0p** [erebe/personal-server#18]
Hi 👋 

We all ♥️ automation.

Flux is a great tool for managing your cluster based on the state of your Git repo, it works like ArgoCD but much easier IMO to install and manage.

Renovate can scan your repository and offer up PRs for image or helm chart updates.

Anyways this all seems to really fit real well with your goals of this repo. Check out my home cluster repo if you are curious about how I and others have done this:

https://github.com/onedr0p/home-cluster

**Comment by erebe** [comment]
Going to take a look at it when having some free time :)
Thank you for letting me know
