### ISSUE TITLE
Where are your postfix and dovecot docker images coming from?

### ISSUE THREAD

**Issue by lsmoura** [erebe/personal-server#4]
* Can we have the Dockerfile for them?
* Can we have a plaintext sample of the fetchmailrc that is used by the postfix image?

Thanks!

**Comment by erebe** [comment]
Both are in the repo, respectively: 
- https://github.com/erebe/personal-server/blob/master/dovecot/Dockerfile
- https://github.com/erebe/personal-server/blob/master/postfix/Dockerfile

They are published thanks to the GitHub action.

For the fetchmailrc, here you go

```
        timeout 300
        antispam -1
        batchlimit 100
        set postmaster erebe

        poll mail.gandi.net
                protocol POP3
                no envelope
                user "erebe@erebe.eu" there
                with password "xxxx"
                is erebe here
                no keep
```
