### ISSUE TITLE
Consider using adnanh/webhook for the automatic deployment part?

### ISSUE THREAD

**Issue by adnanh** [erebe/personal-server#7]
Good read!

> The part left to do yet, is automatic deployment when a new image is build. Ideally, I would like to avoid having to store my kubeconfig inside GitHub secrets and code an app that support web hook in order to trigger a new deployment. But for now I am still thinking of how to do that properly, so I am left to delete manually my pod to re-fetch the latest image until then ¯\(ツ)/¯

You might want to consider using https://github.com/adnanh/webhook for catching the docker image push hook and running your script :-)

**Comment by erebe** [comment]
Thank you, I will spend time this week-end to look into it

**Comment by StarpTech** [comment]
I see no issue to use secrets in Github CI. Github Secrets are encrypted and can only be accessed by specific actions. 

> But for now I am still thinking of how to do that properly, so I am left to delete manually my pod to re-fetch the latest image until then ¯(ツ)/¯

Use skaffold! It was built for that use case.

**Comment by erebe** [comment]
@StarpTech I am going to use webhook in my setup as it allow me to avoids re-uploading to github my kube config in case I change it (Ok, it is unlikely). But I am going to add your example, as it is simpler than setting-up a webhook.

**Comment by StarpTech** [comment]
It's not only about triggering. How you do create immutable image tags? Additionally, skaffold provides a pipeline to build, tag, and deploy to your cluster.

**Comment by erebe** [comment]
Basically, it boils down to the fact that I don't want to open the kube-apiserver to the external world. Right now, the only way to access it is to be a member of my VPN network, if you are coming from internet it is not reachable.
So the solution of using skaffold is not possible in my scenario.

I agree with you, if I had been building the CI/CD of a company, I would have used Skaffold as it does everything for me.
But as I don't tag my personal/custom images also (I use :latest) and that I don't want to expose the apiserver, weebhook here we go !

**Comment by StarpTech** [comment]
Make sense :+1:

**Comment by erebe** [comment]
Closing the issue, I have added a section regarding automatic deployment and a note about skaffold.
Thanks for your feedbacks @StarpTech and @adnanh  👍
